source 'https://rubygems.org'

gem 'pry'
gem 'rack'
gem 'rack-test'
gem 'rspec'
gem 'rack-cors'
gem 'shotgun'
gem "require_all"
gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "sqlite3"
gem "activerecord_reset_pk_sequence"

gem "faker", "~> 2.9"